export enum ActivityEventType {
    ACTIVITY_RESULT = "ACTIVITY_RESULT",
    BACK_PRESSED = "BACK_PRESSED"
}

export enum NavigationErrorMessage {
    TARGET_CLASS_NOT_FOUND = "TARGET_CLASS_NOT_FOUND",
    TARGET_PACKAGE_NOT_FOUND = "TARGET_PACKAGE_NOT_FOUND",
    TARGET_CLASS_NOT_EXPORTED = "TARGET_CLASS_NOT_EXPORTED"
}